# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in hello.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem 'memory_profiler'
gem 'pry'

gem 'zigrb', path: '../../'
